// Curated Indian domestic airports (IATA -> city, state, coords). Origin BLR is
// excluded from the picker since it's locked. A *state* can have several airports,
// so the search box matches on city AND state (typing "Kerala" surfaces COK/TRV/CCJ).
// lat/lon are the city centres — good enough for weather + air-quality lookups
// (Open-Meteo, which is coordinate-based and needs no API key).
window.AIRPORTS = [
  { iata: "DEL", city: "Delhi",              state: "Delhi",             lat: 28.65, lon: 77.23 },
  { iata: "BOM", city: "Mumbai",             state: "Maharashtra",       lat: 19.08, lon: 72.88 },
  { iata: "MAA", city: "Chennai",            state: "Tamil Nadu",        lat: 13.08, lon: 80.27 },
  { iata: "CCU", city: "Kolkata",            state: "West Bengal",       lat: 22.57, lon: 88.36 },
  { iata: "HYD", city: "Hyderabad",          state: "Telangana",         lat: 17.39, lon: 78.49 },
  { iata: "COK", city: "Kochi",              state: "Kerala",            lat:  9.93, lon: 76.27 },
  { iata: "TRV", city: "Thiruvananthapuram", state: "Kerala",            lat:  8.52, lon: 76.94 },
  { iata: "CCJ", city: "Kozhikode",          state: "Kerala",            lat: 11.25, lon: 75.78 },
  { iata: "GOI", city: "Goa (Dabolim)",      state: "Goa",               lat: 15.38, lon: 73.83 },
  { iata: "GOX", city: "Goa (Mopa)",         state: "Goa",               lat: 15.74, lon: 73.86 },
  { iata: "PNQ", city: "Pune",               state: "Maharashtra",       lat: 18.52, lon: 73.86 },
  { iata: "NAG", city: "Nagpur",             state: "Maharashtra",       lat: 21.15, lon: 79.09 },
  { iata: "IXU", city: "Aurangabad",         state: "Maharashtra",       lat: 19.88, lon: 75.34 },
  { iata: "AMD", city: "Ahmedabad",          state: "Gujarat",           lat: 23.03, lon: 72.58 },
  { iata: "STV", city: "Surat",              state: "Gujarat",           lat: 21.17, lon: 72.83 },
  { iata: "BDQ", city: "Vadodara",           state: "Gujarat",           lat: 22.31, lon: 73.18 },
  { iata: "RAJ", city: "Rajkot",             state: "Gujarat",           lat: 22.30, lon: 70.80 },
  { iata: "JAI", city: "Jaipur",             state: "Rajasthan",         lat: 26.91, lon: 75.79 },
  { iata: "UDR", city: "Udaipur",            state: "Rajasthan",         lat: 24.58, lon: 73.71 },
  { iata: "JDH", city: "Jodhpur",            state: "Rajasthan",         lat: 26.24, lon: 73.02 },
  { iata: "LKO", city: "Lucknow",            state: "Uttar Pradesh",     lat: 26.85, lon: 80.95 },
  { iata: "VNS", city: "Varanasi",           state: "Uttar Pradesh",     lat: 25.32, lon: 82.97 },
  { iata: "PAT", city: "Patna",              state: "Bihar",             lat: 25.59, lon: 85.14 },
  { iata: "BBI", city: "Bhubaneswar",        state: "Odisha",            lat: 20.30, lon: 85.82 },
  { iata: "IXR", city: "Ranchi",             state: "Jharkhand",         lat: 23.34, lon: 85.31 },
  { iata: "RPR", city: "Raipur",             state: "Chhattisgarh",      lat: 21.25, lon: 81.63 },
  { iata: "IDR", city: "Indore",             state: "Madhya Pradesh",    lat: 22.72, lon: 75.86 },
  { iata: "BHO", city: "Bhopal",             state: "Madhya Pradesh",    lat: 23.26, lon: 77.41 },
  { iata: "JLR", city: "Jabalpur",           state: "Madhya Pradesh",    lat: 23.18, lon: 79.99 },
  { iata: "VTZ", city: "Visakhapatnam",      state: "Andhra Pradesh",    lat: 17.69, lon: 83.22 },
  { iata: "VGA", city: "Vijayawada",         state: "Andhra Pradesh",    lat: 16.51, lon: 80.65 },
  { iata: "TIR", city: "Tirupati",           state: "Andhra Pradesh",    lat: 13.63, lon: 79.42 },
  { iata: "CJB", city: "Coimbatore",         state: "Tamil Nadu",        lat: 11.02, lon: 76.96 },
  { iata: "IXM", city: "Madurai",            state: "Tamil Nadu",        lat:  9.93, lon: 78.12 },
  { iata: "TRZ", city: "Tiruchirappalli",    state: "Tamil Nadu",        lat: 10.79, lon: 78.70 },
  { iata: "IXE", city: "Mangaluru",          state: "Karnataka",         lat: 12.91, lon: 74.86 },
  { iata: "HBX", city: "Hubballi",           state: "Karnataka",         lat: 15.36, lon: 75.12 },
  { iata: "IXC", city: "Chandigarh",         state: "Chandigarh",        lat: 30.73, lon: 76.78 },
  { iata: "ATQ", city: "Amritsar",           state: "Punjab",            lat: 31.63, lon: 74.87 },
  { iata: "DED", city: "Dehradun",           state: "Uttarakhand",       lat: 30.32, lon: 78.03 },
  { iata: "IXJ", city: "Jammu",              state: "Jammu & Kashmir",   lat: 32.73, lon: 74.86 },
  { iata: "SXR", city: "Srinagar",           state: "Jammu & Kashmir",   lat: 34.08, lon: 74.80 },
  { iata: "IXL", city: "Leh",                state: "Ladakh",            lat: 34.17, lon: 77.58 },
  { iata: "GAU", city: "Guwahati",           state: "Assam",             lat: 26.14, lon: 91.74 },
  { iata: "DIB", city: "Dibrugarh",          state: "Assam",             lat: 27.48, lon: 94.91 },
  { iata: "IXS", city: "Silchar",            state: "Assam",             lat: 24.83, lon: 92.78 },
  { iata: "IXB", city: "Bagdogra",           state: "West Bengal",       lat: 26.70, lon: 88.32 },
  { iata: "IXA", city: "Agartala",           state: "Tripura",           lat: 23.83, lon: 91.28 },
  { iata: "IMF", city: "Imphal",             state: "Manipur",           lat: 24.82, lon: 93.94 },
  { iata: "DMU", city: "Dimapur",            state: "Nagaland",          lat: 25.88, lon: 93.77 },
  { iata: "SHL", city: "Shillong",           state: "Meghalaya",         lat: 25.58, lon: 91.89 },
  { iata: "PNY", city: "Puducherry",         state: "Puducherry",        lat: 11.94, lon: 79.81 },
  { iata: "IXZ", city: "Port Blair",         state: "Andaman & Nicobar", lat: 11.62, lon: 92.73 },
];
